### ISSUE TITLE
   assert face[0] == 3, 'only triangular meshes supported (%s)' % file AssertionError: only triangular meshes supported (examples/0_in/mybed.off)

### ISSUE THREAD

**Issue by monacv** [davidstutz/mesh-fusion#9]
```
(tsdf) mona@goku:~/mesh-fusion$ python 1_scale.py --in_dir=examples/0_in/ --out_dir=examples/1_scaled/
[Data] chair_0890.off extents before 0.011903 - 23.024800, -0.878664 - 22.648900, -0.006066 - 31.802500
[Data] chair_0890.off extents after -0.293402 - 0.293402, -0.299963 - 0.299963, -0.405542 - 0.405542
[Data] chair_0894.off extents before -990.899000 - 990.899000, -998.258000 - 1048.230000, -5.927760 - 3039.680000
[Data] chair_0894.off extents after -0.204498 - 0.204498, -0.211173 - 0.211173, -0.314270 - 0.314270
[Data] chair_0891.off extents before -0.590647 - 20.825800, -20.022200 - 0.006084, -0.001209 - 38.110300
[Data] chair_0891.off extents after -0.153503 - 0.153503, -0.143553 - 0.143553, -0.273166 - 0.273166
[Data] chair_0892.off extents before -12.607350 - 12.607350, -14.691700 - 14.691700, -24.758710 - 24.758710
[Data] chair_0892.off extents after -0.212170 - 0.212170, -0.247248 - 0.247248, -0.416667 - 0.416667
[Data] chair_0893.off extents before -8.868970 - 24.766700, -1.640110 - 26.069500, -0.178068 - 40.159300
[Data] chair_0893.off extents after -0.285853 - 0.285853, -0.235490 - 0.235490, -0.342807 - 0.342807
Traceback (most recent call last):
  File "1_scale.py", line 100, in <module>
    app.run()
  File "1_scale.py", line 56, in run
    mesh = common.Mesh.from_off(filepath)
  File "/home/mona/mesh-fusion/common.py", line 471, in from_off
    vertices, faces = read_off(filepath)
  File "/home/mona/mesh-fusion/common.py", line 167, in read_off
    assert face[0] == 3, 'only triangular meshes supported (%s)' % file
AssertionError: only triangular meshes supported (examples/0_in/mybed.off)
```

I have a full bed 3d model downloaded and extracted only the bed frame using Maya into OBJ format. Then used MeshLab to convert the OBJ to OFF format. How can I fix the bed so the above error wouldn't occur?

![Screenshot from 2021-02-01 17-18-49](https://user-images.githubusercontent.com/76495162/106525758-7da73b00-64b2-11eb-8a5f-65ba6eedad4c.png)

Also: https://stackoverflow.com/questions/66001261/convert-a-maya-exported-obj-file-into-a-triangular-mesh-off-file-assertionerr

**Comment by monacv** [comment]
also a comment that when I marked off 'polygonal' in meshlab when converting Maya-produced OBJ file into OFF file, I got this new error:

```
(tsdf) mona@goku:~/mesh-fusion$ python 1_scale.py --in_dir=examples/0_in/ --out_dir=examples/1_scaled/
[Data] chair_0890.off extents before 0.011903 - 23.024800, -0.878664 - 22.648900, -0.006066 - 31.802500
[Data] chair_0890.off extents after -0.293402 - 0.293402, -0.299963 - 0.299963, -0.405542 - 0.405542
[Data] chair_0894.off extents before -990.899000 - 990.899000, -998.258000 - 1048.230000, -5.927760 - 3039.680000
[Data] chair_0894.off extents after -0.204498 - 0.204498, -0.211173 - 0.211173, -0.314270 - 0.314270
[Data] chair_0891.off extents before -0.590647 - 20.825800, -20.022200 - 0.006084, -0.001209 - 38.110300
[Data] chair_0891.off extents after -0.153503 - 0.153503, -0.143553 - 0.143553, -0.273166 - 0.273166
[Data] chair_0892.off extents before -12.607350 - 12.607350, -14.691700 - 14.691700, -24.758710 - 24.758710
[Data] chair_0892.off extents after -0.212170 - 0.212170, -0.247248 - 0.247248, -0.416667 - 0.416667
[Data] chair_0893.off extents before -8.868970 - 24.766700, -1.640110 - 26.069500, -0.178068 - 40.159300
[Data] chair_0893.off extents after -0.285853 - 0.285853, -0.235490 - 0.235490, -0.342807 - 0.342807
Traceback (most recent call last):
  File "1_scale.py", line 100, in <module>
    app.run()
  File "1_scale.py", line 56, in run
    mesh = common.Mesh.from_off(filepath)
  File "/home/mona/mesh-fusion/common.py", line 471, in from_off
    vertices, faces = read_off(filepath)
  File "/home/mona/mesh-fusion/common.py", line 166, in read_off
    assert face[0] == len(face) - 1, 'face should have %d vertices but as %d (%s)' % (face[0], len(face) - 1, file)
AssertionError: face should have 3 vertices but as 6 (examples/0_in/mybed.off)

```

**Comment by monacv** [comment]
The answer is here: https://stackoverflow.com/a/66003814/2414957
`sed 's/192\ 192\ 192$//' mybed1.off > mybed2.off`
